version: '3'
services:
  mqtt:
    image: 'emqx/emqx:4.3.10'
    container_name: mqtt-server
    restart: always
    environment:
      - EMQX_HOST=0.0.0.0
    ports:
      - '1883:1883'
      - '8084:8084'
      - '8883:8883'
      - '18083:18083'
