// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.20.1
// source: mq_rpc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MqRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body   string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *MqRpcRequest) Reset() {
	*x = MqRpcRequest{}
	mi := &file_mq_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqRpcRequest) ProtoMessage() {}

func (x *MqRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqRpcRequest.ProtoReflect.Descriptor instead.
func (*MqRpcRequest) Descriptor() ([]byte, []int) {
	return file_mq_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *MqRpcRequest) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *MqRpcRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type MqRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MqRpcResponse) Reset() {
	*x = MqRpcResponse{}
	mi := &file_mq_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqRpcResponse) ProtoMessage() {}

func (x *MqRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mq_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqRpcResponse.ProtoReflect.Descriptor instead.
func (*MqRpcResponse) Descriptor() ([]byte, []int) {
	return file_mq_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *MqRpcResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MqRpcResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mq_rpc_proto protoreflect.FileDescriptor

var file_mq_rpc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x71, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6d, 0x71, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x3a, 0x0a, 0x0c, 0x4d, 0x71, 0x52, 0x70, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0x3d, 0x0a, 0x0d, 0x4d, 0x71, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x55, 0x0a, 0x13, 0x4d, 0x71, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52,
	0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x71, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x71, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x71, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x71, 0x52, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mq_rpc_proto_rawDescOnce sync.Once
	file_mq_rpc_proto_rawDescData = file_mq_rpc_proto_rawDesc
)

func file_mq_rpc_proto_rawDescGZIP() []byte {
	file_mq_rpc_proto_rawDescOnce.Do(func() {
		file_mq_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mq_rpc_proto_rawDescData)
	})
	return file_mq_rpc_proto_rawDescData
}

var file_mq_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mq_rpc_proto_goTypes = []any{
	(*MqRpcRequest)(nil),  // 0: mq_grpc.MqRpcRequest
	(*MqRpcResponse)(nil), // 1: mq_grpc.MqRpcResponse
}
var file_mq_rpc_proto_depIdxs = []int32{
	0, // 0: mq_grpc.MqGreeterRpcService.SendMqMessage:input_type -> mq_grpc.MqRpcRequest
	1, // 1: mq_grpc.MqGreeterRpcService.SendMqMessage:output_type -> mq_grpc.MqRpcResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mq_rpc_proto_init() }
func file_mq_rpc_proto_init() {
	if File_mq_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mq_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mq_rpc_proto_goTypes,
		DependencyIndexes: file_mq_rpc_proto_depIdxs,
		MessageInfos:      file_mq_rpc_proto_msgTypes,
	}.Build()
	File_mq_rpc_proto = out.File
	file_mq_rpc_proto_rawDesc = nil
	file_mq_rpc_proto_goTypes = nil
	file_mq_rpc_proto_depIdxs = nil
}
